mode:
    default: server
    other: [local]

loading_screen:
    default: true
    other: [false]

loading_theme:
    default: vhelix
    other: ["*"]

# Use pure js instead unless this pkg is pushed to CRAN
# loading_particles:
#     default: false
#     other: [true]

use_crayon:
    default: true
    other: [false]

# will work on this option once `shinymeta` is on CRAN
#display_code:
#    default: false
#    other: [true]

verbose:
    default: false
    other: [true]

admin_page:
    default: false
    other: [true]

admin_url:
    default: admin
    other: ["*"]

warning_toast:
    default: true
    other: [false]
