mode:
    default: local
    other: [server]

loading_screen:
    default: true
    other: [false]

loading_theme:
    default: vhelix
    other: ["*"]

# Use pure js instead unless this pkg is pushed to CRAN
# loading_particles:
#     default: false
#     other: [true]

use_crayon:
    default: true
    other: [false]

# will work on this option once `shinymeta` is on CRAN
#display_code:
#    default: false
#    other: [true]

verbose:
    default: false
    other: [true]

admin_page:
    default: false
    other: [true]

admin_url:
    default: admin
    other: ["*"]

warning_toast:
    default: true
    other: [false]

module_wf:
    default: true
    other: [false]

module_rnaseq:
    default: true
    other: [false]

module_ggplot:
    default: true
    other: [false]

tab_welcome:
    default: true
    other: [false]

tab_module_main:
    default: true
    other: [false]

tab_vs_main:
    default: true
    other: [false]

tab_canvas:
    default: true
    other: [false]

tab_about:
    default: true
    other: [false]

note_url:
    default: 'https://raw.githubusercontent.com/systemPipeR/systemPipeShiny/master/inst/remote_resource/notifications.yaml'
    other: ['*']

