mode:
    default: local
    other: [server]

loading_screen:
    default: true
    other: [false]

loading_theme:
    default: vhelix
    other: ["404"]


loading_particles:
    default: false
    other: [true]

use_crayon:
    default: true
    other: [false]

# will work on this option once `shinymeta` is on CRAN
#display_code:
#    default: false
#    other: [true]

verbose:
    default: false
    other: [true]

dev:
    default: false
    other: [true]

admin_page:
    default: false
    other: [true]

admin_url:
    default: admin
    other: ["*"]

warning_toast:
    default: true
    other: [false]
