mode:
    default: local
    other: [server]

loading_screen:
    default: true
    other: [false]

loading_theme:
    default: 404
    other: [vhelix]


loading_particles:
    default: true
    other: [false]

use_crayon:
    default: true
    other: [false]
